version: "3"

services:
  database:
    image: postgres:14.0-alpine
    container_name: teachtolearn-database-dev
    network_mode: "host"
    environment:
      POSTGRES_DB: "ttl"
      POSTGRES_USER: "teachtolearn"
      POSTGRES_PASSWORD: "postgresqlpassword"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: teachtolearn-backend-dev
    network_mode: "host"
    command: >
      bash -c "flask createdb
      && flask run --host=0.0.0.0"
    env_file:
      - backend/.env
    depends_on:
      - database
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: teachtolearn-frontend-dev
    network_mode: "host"
    command: "node --inspect --trace-warnings build"
    depends_on:
      - backend
    restart: always
