version: "3"

services:
  database:
    image: postgres:14.0-alpine
    container_name: teachtolearn-db
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data 
      - ./backend/init.sql:/docker-entrypoint-initdb.d/00-init.sql
    env_file:
      - .env.prod
    networks:
      - web

  backend:
    image: registry.gitlab.com/rcastellotti/teachtolearn/backend:latest
    container_name: teachtolearn-backend
    env_file:
      - .env.prod
    command: >
      ash -c "flask createdb
      && gunicorn --bind 0.0.0.0:5000 ttl:app"
    ports:
      - 13001:5000
    depends_on:
      - "database"
    restart: always
    networks:
      - web
    labels:
      - traefik.http.routers.teachtolearn-backend.rule=Host(`teachtolearn.club`) && PathPrefix(`/api`)
      - traefik.http.routers.teachtolearn-backend.tls=true
      - traefik.http.routers.teachtolearn-backend.tls.certresolver=lets-encrypt
      - traefik.port=13001

  frontend:
    image: registry.gitlab.com/rcastellotti/teachtolearn/frontend:latest
    container_name: teachtolearn-frontend
    restart: always
    command: "node build"
    ports:
      - 13000:3000
    depends_on:
      - "backend"
    networks:
      - web
    labels:
      - traefik.http.routers.teachtolearn-frontend.rule=Host(`teachtolearn.club`)
      - traefik.http.routers.teachtolearn-frontend.tls=true
      - traefik.http.routers.teachtolearn-frontend.tls.certresolver=lets-encrypt
      - traefik.port=13000
  
  slides:
    image: registry.gitlab.com/rcastellotti/teachtolearn/slidev:latest
    container_name: teachtolearn-slides
    ports:
      - 8889:3000
    restart: always
    command: npm run serve
    networks:
      - web
    labels:
      - traefik.http.routers.teachtolearn-slides.rule=Host(`slides.teachtolearn.club`) 
      - traefik.http.routers.teachtolearn-slides.tls=true
      - traefik.http.routers.teachtolearn-slides.tls.certresolver=lets-encrypt
      - traefik.port=8889
  
  docs:
    image: docker.io/node:17-alpine
    container_name: teachtolearn-docs
    command: >
      ash -c "npx insomnia-documenter --config insomnia.json 
      && npx serve"
    ports:
      - 5100:3000
    volumes:
      - "./insomnia.json:/insomnia.json"
    restart: always
    networks:
      - web
    labels:
      - traefik.http.routers.teachtolearn-docs.rule=Host(`docs.teachtolearn.club`) 
      - traefik.http.routers.teachtolearn-docs.tls=true
      - traefik.http.routers.teachtolearn-docs.tls.certresolver=lets-encrypt
      - traefik.port=5100

networks:
  web:
    external: true

