version: "3.3"

networks:
  default:
    external:
      name: teachtolearn

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    expose:
      - 9000
      - 9001
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: <username>
      MINIO_ROOT_PASSWORD: <password>
      MINIO_BROWSER_REDIRECT_URL: https://s3console.teachtolearn.club
      MINIO_SERVER_URL: https://s3.teachtolearn.club
    labels:
      - traefik.enable=true
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.rule=Host(`s3.teachtolearn.club`)
      - traefik.http.routers.minio.tls.certresolver=le
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      - traefik.http.routers.minio-console.rule=Host(`s3console.teachtolearn.club`)
      - traefik.http.routers.minio-console.tls.certresolver=le
      - traefik.http.routers.minio-console.entrypoints=websecure
      - traefik.http.routers.minio-console.service=minio-console
