[http.middlewares.simpleAuth.basicAuth]
  users = [
    "<htpasswd -nb username password>"
  ]

[http.routers.api]
  rule = "Host(`monitor.teachtolearn.club`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
